-- ============================================
-- 한국 주요 기업 시드 데이터
-- 상장사 + 주요 비상장 기업 + IT/클라우드 기업
-- Supabase SQL Editor에서 실행
-- ============================================

INSERT INTO companies (name, official_name, status) VALUES
-- 대기업 / 그룹사
('삼성전자', '삼성전자', 'verified'),
('삼성SDS', '삼성SDS', 'verified'),
('삼성물산', '삼성물산', 'verified'),
('삼성생명', '삼성생명', 'verified'),
('삼성화재', '삼성화재', 'verified'),
('삼성증권', '삼성증권', 'verified'),
('삼성SDI', '삼성SDI', 'verified'),
('삼성전기', '삼성전기', 'verified'),
('삼성바이오로직스', '삼성바이오로직스', 'verified'),
('삼성엔지니어링', '삼성엔지니어링', 'verified'),
('SK하이닉스', 'SK하이닉스', 'verified'),
('SK텔레콤', 'SK텔레콤', 'verified'),
('SK이노베이션', 'SK이노베이션', 'verified'),
('SK스퀘어', 'SK스퀘어', 'verified'),
('SKC', 'SKC', 'verified'),
('SK네트웍스', 'SK네트웍스', 'verified'),
('SK바이오팜', 'SK바이오팜', 'verified'),
('SK케미칼', 'SK케미칼', 'verified'),
('LG전자', 'LG전자', 'verified'),
('LG화학', 'LG화학', 'verified'),
('LG에너지솔루션', 'LG에너지솔루션', 'verified'),
('LG디스플레이', 'LG디스플레이', 'verified'),
('LG이노텍', 'LG이노텍', 'verified'),
('LG유플러스', 'LG유플러스', 'verified'),
('LG CNS', 'LG CNS', 'verified'),
('LG생활건강', 'LG생활건강', 'verified'),
('현대자동차', '현대자동차', 'verified'),
('기아', '기아', 'verified'),
('현대모비스', '현대모비스', 'verified'),
('현대건설', '현대건설', 'verified'),
('현대중공업', '현대중공업', 'verified'),
('현대오토에버', '현대오토에버', 'verified'),
('현대글로비스', '현대글로비스', 'verified'),
('롯데쇼핑', '롯데쇼핑', 'verified'),
('롯데케미칼', '롯데케미칼', 'verified'),
('롯데정보통신', '롯데정보통신', 'verified'),
('롯데이노베이트', '롯데이노베이트', 'verified'),
('포스코', 'POSCO홀딩스', 'verified'),
('포스코ICT', '포스코DX', 'verified'),
('한화솔루션', '한화솔루션', 'verified'),
('한화에어로스페이스', '한화에어로스페이스', 'verified'),
('한화시스템', '한화시스템', 'verified'),
('한화생명', '한화생명', 'verified'),
('두산에너빌리티', '두산에너빌리티', 'verified'),
('두산밥캣', '두산밥캣', 'verified'),
('CJ제일제당', 'CJ제일제당', 'verified'),
('CJ대한통운', 'CJ대한통운', 'verified'),
('CJ ENM', 'CJ ENM', 'verified'),
('CJ올리브네트웍스', 'CJ올리브네트웍스', 'verified'),
('GS칼텍스', 'GS칼텍스', 'verified'),
('GS리테일', 'GS리테일', 'verified'),
('GS건설', 'GS건설', 'verified'),
('LS일렉트릭', 'LS일렉트릭', 'verified'),
('효성', '효성', 'verified'),
('효성TNS', '효성TNS', 'verified'),
('신세계', '신세계', 'verified'),
('이마트', '이마트', 'verified'),
-- 통신 / 미디어
('KT', 'KT', 'verified'),
('KT클라우드', 'KT클라우드', 'verified'),
('KTds', 'KTds', 'verified'),
('LG헬로비전', 'LG헬로비전', 'verified'),
('카카오', '카카오', 'verified'),
('카카오엔터프라이즈', '카카오엔터프라이즈', 'verified'),
('카카오뱅크', '카카오뱅크', 'verified'),
('카카오페이', '카카오페이', 'verified'),
('카카오모빌리티', '카카오모빌리티', 'verified'),
('네이버', '네이버', 'verified'),
('네이버클라우드', '네이버클라우드', 'verified'),
('네이버웹툰', '네이버웹툰', 'verified'),
('라인플러스', '라인플러스', 'verified'),
('쿠팡', '쿠팡', 'verified'),
('배달의민족', '우아한형제들', 'verified'),
('토스', '비바리퍼블리카', 'verified'),
('당근마켓', '당근', 'verified'),
('야놀자', '야놀자', 'verified'),
-- IT / 클라우드 / SaaS
('클루커스', '클루커스', 'verified'),
('메가존클라우드', '메가존클라우드', 'verified'),
('베스핀글로벌', '베스핀글로벌', 'verified'),
('솔트웨어', '솔트웨어', 'verified'),
('NHN클라우드', 'NHN클라우드', 'verified'),
('NHN', 'NHN', 'verified'),
('NHN커머스', 'NHN커머스', 'verified'),
('가비아', '가비아', 'verified'),
('더존비즈온', '더존비즈온', 'verified'),
('한글과컴퓨터', '한글과컴퓨터', 'verified'),
('안랩', '안랩', 'verified'),
('이스트소프트', '이스트소프트', 'verified'),
('넷마블', '넷마블', 'verified'),
('엔씨소프트', '엔씨소프트', 'verified'),
('크래프톤', '크래프톤', 'verified'),
('넥슨', '넥슨', 'verified'),
('스마일게이트', '스마일게이트', 'verified'),
('펄어비스', '펄어비스', 'verified'),
('위메이드', '위메이드', 'verified'),
('카카오게임즈', '카카오게임즈', 'verified'),
-- SI / IT서비스
('삼성SDS', '삼성SDS', 'verified'),
('현대오토에버', '현대오토에버', 'verified'),
('LG CNS', 'LG CNS', 'verified'),
('SK C&C', 'SK C&C', 'verified'),
('한국IBM', '한국IBM', 'verified'),
('한국마이크로소프트', '한국마이크로소프트', 'verified'),
('한국오라클', '한국오라클', 'verified'),
('한국HP', '한국HP', 'verified'),
('한국델테크놀로지스', '한국델테크놀로지스', 'verified'),
('SAP코리아', 'SAP코리아', 'verified'),
('AWS코리아', 'AWS코리아', 'verified'),
('구글코리아', '구글코리아', 'verified'),
('티맥스소프트', '티맥스소프트', 'verified'),
('알티베이스', '알티베이스', 'verified'),
-- 금융
('KB국민은행', 'KB국민은행', 'verified'),
('KB금융그룹', 'KB금융그룹', 'verified'),
('신한은행', '신한은행', 'verified'),
('신한금융그룹', '신한금융그룹', 'verified'),
('하나은행', '하나은행', 'verified'),
('하나금융그룹', '하나금융그룹', 'verified'),
('우리은행', '우리은행', 'verified'),
('우리금융그룹', '우리금융그룹', 'verified'),
('NH농협은행', 'NH농협은행', 'verified'),
('IBK기업은행', 'IBK기업은행', 'verified'),
('한국산업은행', '한국산업은행', 'verified'),
('한국수출입은행', '한국수출입은행', 'verified'),
('미래에셋증권', '미래에셋증권', 'verified'),
('한국투자증권', '한국투자증권', 'verified'),
('삼성자산운용', '삼성자산운용', 'verified'),
('교보생명', '교보생명', 'verified'),
('한화손해보험', '한화손해보험', 'verified'),
('DB손해보험', 'DB손해보험', 'verified'),
-- 제조 / 건설 / 에너지
('한국전력', '한국전력공사', 'verified'),
('한국가스공사', '한국가스공사', 'verified'),
('한국수력원자력', '한국수력원자력', 'verified'),
('현대에너지솔루션', '현대에너지솔루션', 'verified'),
('대우건설', '대우건설', 'verified'),
('대림산업', 'DL이앤씨', 'verified'),
('호반건설', '호반건설', 'verified'),
('태영건설', '태영건설', 'verified'),
('아모레퍼시픽', '아모레퍼시픽', 'verified'),
('LG생활건강', 'LG생활건강', 'verified'),
('오뚜기', '오뚜기', 'verified'),
('농심', '농심', 'verified'),
('풀무원', '풀무원', 'verified'),
('삼양식품', '삼양식품', 'verified'),
('한국타이어', '한국타이어앤테크놀로지', 'verified'),
-- 유통 / 물류
('SSG닷컴', 'SSG닷컴', 'verified'),
('11번가', '십일번가', 'verified'),
('인터파크', '인터파크', 'verified'),
('무신사', '무신사', 'verified'),
('마켓컬리', '컬리', 'verified'),
('한진', '한진', 'verified'),
('CJ대한통운', 'CJ대한통운', 'verified'),
('로젠택배', '로젠택배', 'verified'),
-- 헬스케어 / 바이오
('셀트리온', '셀트리온', 'verified'),
('SK바이오사이언스', 'SK바이오사이언스', 'verified'),
('한미약품', '한미약품', 'verified'),
('유한양행', '유한양행', 'verified'),
('대웅제약', '대웅제약', 'verified'),
('녹십자', '녹십자', 'verified'),
('종근당', '종근당', 'verified'),
-- 공공 / 교육
('한국과학기술원', 'KAIST', 'verified'),
('서울대학교', '서울대학교', 'verified'),
('한국전자통신연구원', 'ETRI', 'verified'),
('한국인터넷진흥원', 'KISA', 'verified'),
('정보통신산업진흥원', 'NIPA', 'verified'),
('한국데이터산업진흥원', 'KData', 'verified'),
('국민건강보험공단', '국민건강보험공단', 'verified'),
('한국토지주택공사', 'LH', 'verified'),
('한국도로공사', '한국도로공사', 'verified'),
('인천국제공항공사', '인천국제공항공사', 'verified')
ON CONFLICT (name) DO UPDATE SET official_name = EXCLUDED.official_name, status = 'verified';

-- 주요 별칭 등록
INSERT INTO company_aliases (company_id, alias_name)
SELECT c.id, a.alias FROM (VALUES
  ('삼성전자', 'Samsung Electronics'),
  ('삼성전자', 'Samsung'),
  ('삼성전자', '삼성'),
  ('SK하이닉스', 'SK Hynix'),
  ('LG전자', 'LG Electronics'),
  ('LG전자', 'LG'),
  ('현대자동차', 'Hyundai Motor'),
  ('현대자동차', '현대차'),
  ('카카오', 'Kakao'),
  ('네이버', 'Naver'),
  ('네이버', 'NAVER'),
  ('쿠팡', 'Coupang'),
  ('클루커스', 'Cloocus'),
  ('메가존클라우드', 'Megazone Cloud'),
  ('베스핀글로벌', 'Bespin Global'),
  ('한국마이크로소프트', 'Microsoft Korea'),
  ('한국마이크로소프트', 'MS코리아'),
  ('AWS코리아', 'Amazon Web Services Korea'),
  ('AWS코리아', 'AWS'),
  ('구글코리아', 'Google Korea'),
  ('구글코리아', 'Google'),
  ('KB국민은행', 'KB Bank'),
  ('신한은행', 'Shinhan Bank'),
  ('KT', 'KT Corp'),
  ('포스코', 'POSCO'),
  ('토스', 'Toss'),
  ('배달의민족', '배민'),
  ('당근마켓', '당근')
) AS a(company_name, alias)
JOIN companies c ON c.name = a.company_name
ON CONFLICT DO NOTHING;
